apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: python-tre4-yde4r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-tre4-yde4r 
  name: python-tre4-yde4r
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: python-tre4-yde4r 
